"use client";

import { useState } from "react";
import { zipSync, strToU8 } from "fflate";
import { trackEvent } from "@/lib/analytics";
import { AffiliateButton } from "./AffiliateButton";

export function WebsiteMarkdownTool() {
  const [domain, setDomain] = useState(""); const [urls, setUrls] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]);
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [converting, setConverting] = useState(false); const [output, setOutput] = useState("");
  async function discover(event: React.FormEvent) { event.preventDefault(); trackEvent("tool_start", { source_component: "website_markdown_form", tool_name: "website_to_markdown", result_state: "pending" }); setLoading(true); setError(""); setUrls([]); setSelected([]); setOutput(""); try { const response = await fetch("/api/discover", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ domain }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setUrls(data.urls); setSelected(data.urls.slice(0, 5)); trackEvent("tool_success", { source_component: "website_markdown_form", tool_name: "website_to_markdown", result_state: "success" }); } catch (err) { const message = err instanceof Error ? err.message : "Unable to discover this site."; setError(message); trackEvent("tool_error", { source_component: "website_markdown_form", tool_name: "website_to_markdown", result_state: "error", error_message: message }); } finally { setLoading(false); } }
  function toggle(url: string) { setSelected((current) => current.includes(url) ? current.filter((item) => item !== url) : current.length < 10 ? [...current, url] : current); }
  async function convert() { setConverting(true); setError(""); setOutput(""); try { const sections: string[] = []; for (const url of selected) { const response = await fetch("/api/markdown", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) throw new Error(`${url}: ${data.error || "conversion failed"}`); sections.push(`\n\n<!-- Source: ${data.sourceUrl} -->\n\n${data.markdown}`); } setOutput(sections.join("\n")); trackEvent("tool_success", { source_component: "website_markdown_batch", tool_name: "website_to_markdown", result_state: "success" }); } catch (err) { const message = err instanceof Error ? err.message : "Unable to convert the selected pages."; setError(message); trackEvent("tool_error", { source_component: "website_markdown_batch", tool_name: "website_to_markdown", result_state: "error", error_message: message }); } finally { setConverting(false); } }
  function downloadMarkdown() { if (!output) return; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([output], { type: "text/markdown" })); link.download = "website.md"; link.click(); URL.revokeObjectURL(link.href); trackEvent("download_result", { source_component: "website_markdown_result", tool_name: "website_to_markdown", result_state: "success", download_format: "markdown" }); }
  function downloadZip() { if (!output) return; const bytes = zipSync({ "website.md": strToU8(output) }); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([bytes], { type: "application/zip" })); link.download = "website-markdown.zip"; link.click(); URL.revokeObjectURL(link.href); trackEvent("download_result", { source_component: "website_markdown_result", tool_name: "website_to_markdown", result_state: "success", download_format: "zip" }); }
  return <div className="tool-panel"><form onSubmit={discover}><label className="field-label" htmlFor="domain">Website domain</label><div className="url-row"><input className="url-input" id="domain" value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="example.com" required /><button className="button primary" type="submit" disabled={loading}>{loading ? "Discovering…" : "Discover sitemap"}</button></div><p className="tool-help">Find up to 50 sitemap URLs, then select up to 10 for your own batch.</p></form>{error && <div className="tool-error" role="alert">{error}</div>}{urls.length > 0 && <div className="result-panel"><div className="result-head"><div><h2>Select pages</h2><p className="tool-help">{selected.length} of {urls.length} selected</p></div><div className="result-actions"><button className="button secondary" type="button" onClick={() => setSelected(urls.slice(0, 10))}>Select first 10</button><button className="button primary" type="button" disabled={!selected.length || converting} onClick={convert}>{converting ? "Converting…" : "Convert selected"}</button></div></div><div className="url-list">{urls.map((url) => <label key={url} className="url-item"><input type="checkbox" checked={selected.includes(url)} onChange={() => toggle(url)} /><span>{url}</span></label>)}</div>{output && <><div className="result-head" style={{ marginTop: 18 }}><h2>Markdown batch</h2><div className="result-actions"><button className="button secondary" type="button" onClick={downloadMarkdown}>Download .md</button><button className="button secondary" type="button" onClick={downloadZip}>Download .zip</button></div></div><pre className="markdown-output">{output}</pre></>}<div className="affiliate-card"><div><span className="eyebrow">Batch limit</span><h3>Need to crawl the entire website?</h3><p>This starter tool handles up to 10 selected URLs. Larger crawls need queues, retries, and rendering controls.</p></div><AffiliateButton placement="tool-result" sourceComponent="tool_result_cta" toolName="website_to_markdown" resultState={output ? "success" : "idle"}>Crawl with Firecrawl</AffiliateButton></div></div>}</div>;
}
