import Link from "next/link";
import { PageShell } from "@/components/PageShell";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Free Web Data Tools", "Browse free web data tools for URL to Markdown, webpage conversion, website batches, llms.txt generation, and link extraction, with clear limits.", "/tools");

const tools = [["URL to Markdown", "Convert one public page into Markdown.", "/tools/url-to-markdown"], ["Webpage to Markdown", "A focused single-webpage workflow.", "/tools/webpage-to-markdown"], ["Website to Markdown", "Select sitemap pages and download a batch.", "/tools/website-to-markdown"], ["llms.txt generator", "Create a curated AI discovery file.", "/tools/llms-txt-generator"], ["URL extractor", "List internal and external links.", "/tools/url-extractor"]] as const;

export default function ToolsHub() {
  return <PageShell><div className="container narrow"><div className="breadcrumbs"><Link href="/">Home</Link><span className="crumb-sep">/</span><span>Tools</span></div><div className="page-hero"><span className="eyebrow">Free utilities</span><h1>Free web data tools for small, clear jobs.</h1><p className="lede">These free web data tools start with one public URL or sitemap task, then move to a managed crawling workflow when the scope grows. Choose these free web data tools by the size and format of your first result.</p></div><div className="card-grid">{tools.map(([title, description, href]) => <Link className="card" href={href} key={href}><h2>{title}</h2><p>{description}</p><span className="text-link">Open tool →</span></Link>)}</div><div className="prose section"><h2>Choose a free web data tool by the job</h2><p>Use URL to Markdown when you know one public page and want a readable copy. Use Webpage to Markdown for the same single-page workflow when the page is going into notes, prompts, or documentation. Use Website to Markdown when a sitemap already gives you a short list of pages to select.</p><p>The llms.txt generator is for curating links that AI systems and developers should discover. The URL extractor is for link inventory: it separates internal and external destinations without pretending to validate or crawl every result. These free web data tools are deliberately small, so the first output is easy to inspect.</p><h2>What each free web data tool returns</h2><ul><li><strong>URL to Markdown:</strong> a readable result from one public URL.</li><li><strong>Website to Markdown:</strong> selected sitemap pages combined into a reviewable batch.</li><li><strong>llms.txt generator:</strong> a curated plain-text directory of important URLs.</li><li><strong>URL extractor:</strong> internal and external links with totals and exports.</li></ul><p>These free web data tools make the first result visible before you choose a larger workflow. Check the output against the original page and keep only the pages your project can use.</p><h2>Know the limits before you scale</h2><p>All five free web data tools work best with public inputs. Login walls, JavaScript-only content, anti-bot challenges, large responses, and private network addresses can produce an error or incomplete result. For scheduled crawls, retries, browser rendering, proxy controls, or structured extraction across hundreds of URLs, move to a managed API after testing a representative sample.</p><p>These free web data tools are a starting point, not a promise of unlimited crawling. The free web data tools keep the first result focused, so you can save it and decide whether a larger workflow is justified. Compare free web data tools by the input, output, and limit that matter for your next task. Start with free web data tools when you need an inspectable first result. This free web data tools directory is organized around the result you need first.</p></div></div></PageShell>;
}
