import Link from "next/link";
import { PageShell } from "@/components/PageShell";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Free Web Data Tools", "Browse free tools for URL to Markdown, webpage conversion, website batches, llms.txt generation, and link extraction, with clear limits.", "/tools");

const tools = [["URL to Markdown", "Convert one public page into Markdown.", "/tools/url-to-markdown"], ["Webpage to Markdown", "A focused single-webpage workflow.", "/tools/webpage-to-markdown"], ["Website to Markdown", "Select sitemap pages and download a batch.", "/tools/website-to-markdown"], ["llms.txt generator", "Create a curated AI discovery file.", "/tools/llms-txt-generator"], ["URL extractor", "List internal and external links.", "/tools/url-extractor"]] as const;

export default function ToolsHub() {
  return <PageShell><div className="container narrow"><div className="breadcrumbs"><Link href="/">Home</Link><span className="crumb-sep">/</span><span>Tools</span></div><div className="page-hero"><span className="eyebrow">Free utilities</span><h1>Free web data tools for small, clear jobs.</h1><p className="lede">Start with one public URL or a short sitemap task. Review the first result, then choose a larger crawling workflow only when your project needs it.</p></div><div className="card-grid">{tools.map(([title, description, href]) => <Link className="card" href={href} key={href}><h2>{title}</h2><p>{description}</p><span className="text-link">Open tool -&gt;</span></Link>)}</div><div className="prose section"><h2>Choose a tool by the job</h2><p>Use URL to Markdown or Webpage to Markdown for one public page. Use Website to Markdown when a sitemap gives you a short list of pages to select. The llms.txt generator creates an editable directory of important URLs, while the URL extractor inventories internal and external destinations.</p><h2>What the tools return</h2><ul><li><strong>URL and Webpage to Markdown:</strong> a readable result from one public page.</li><li><strong>Website to Markdown:</strong> selected sitemap pages combined into a reviewable batch.</li><li><strong>llms.txt generator:</strong> a curated plain-text directory.</li><li><strong>URL extractor:</strong> links with internal and external totals and exports.</li></ul><h2>Know the limits before you scale</h2><p>Public pages work best. Login walls, JavaScript-only content, anti-bot challenges, large responses, and private network addresses can produce an error or incomplete result. For scheduled crawls, browser rendering, retries, proxy controls, or structured extraction across many URLs, test a managed API against representative pages first.</p></div></div></PageShell>;
}
